#!/usr/bin/env python3
"""Section 6 (Results) artifacts: descriptives table + grade-distribution figure.

Reads:  data/full_grades.jsonl  (via grade_binning.load / fit_grades)
Writes: paper/tables/descriptives.tex          (random sample, by platform)
        paper/figures/grade_distribution.pdf    (population grade shares + 95% CIs)

Everything is computed on the representative random historical sample
(in_historical == 1, seed 42); shares are population estimates by standard
survey inference, so 95% CIs come from the binomial normal approximation.

Regenerates on compile via paper/.latexmkrc.

Usage:
    PYTHONPATH=src .venv/bin/python paper/scripts/generate_section6.py
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "paper" / "scripts"))
from _dispute_data import is_genuine, is_confirmed  # noqa: E402
from grade_binning import fit_grades, load  # noqa: E402
from generate_regression_table import auc_matrix  # noqa: E402

TAB_DIR = ROOT / "paper" / "tables"
FIG_DIR = ROOT / "paper" / "figures"


def _ci(k, n):
    """95% normal-approximation CI for a proportion, returned in percent."""
    p = k / n
    se = math.sqrt(p * (1 - p) / n)
    return 100 * p, 100 * max(0.0, p - 1.96 * se), 100 * min(1.0, p + 1.96 * se)


# ---------------------------------------------------------------- descriptives
def descriptives_table(outfile="descriptives.tex", label="tab:descriptives"):
    # rows and units are positionally aligned (grade_binning.load); units carry the
    # series id (``group``), which is absent from the raw full_grades rows.
    rows, units, pop, disp_m, mat_m, conf_m = load()
    plats = [("polymarket", "Polymarket"), ("kalshi", "Kalshi")]
    cols = {}
    for key, _ in plats:
        sel = [(r, u) for r, u, pm in zip(rows, units, pop)
               if pm and r["platform"] == key]
        n = len(sel)
        series = len({u.get("group") for _, u in sel})
        vol = sorted((r.get("volume") or 0) for r, _ in sel)
        disp = sum(r["disputed"] == 1 for r, _ in sel)
        mat = sum(is_genuine(r) for r, _ in sel)
        conf = sum(is_confirmed(r) for r, _ in sel)
        flag = sum(bool(r.get("proposed_prohibited")) for r, _ in sel)
        cols[key] = dict(n=n, series=series, totvol=sum(vol),
                         medvol=vol[n // 2], disp=disp, mat=mat, conf=conf, flag=flag)

    def row(name, fmt):
        return f"{name} & " + " & ".join(fmt(cols[k]) for k, _ in plats) + r" \\"

    money = lambda x: f"\\${x/1e6:,.0f}M" if x >= 1e6 else f"\\${x:,.0f}"
    pct = lambda k, n: f"{100*k/n:.1f}\\%"

    lines = [
        "% auto-generated by paper/scripts/generate_section6.py",
        r"\begin{table}[t]", r"\centering", r"\small",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\caption{The representative market sample}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{lcc}", r"\toprule",
        r" & Polymarket & Kalshi \\", r"\midrule",
        row("Markets", lambda c: f"{c['n']:,}"),
        row("Distinct series", lambda c: f"{c['series']:,}"),
        row("Total dollar volume", lambda c: money(c["totvol"])),
        row("Median market volume", lambda c: money(c["medvol"])),
        r"\addlinespace",
        row("Disputed (all)", lambda c: f"{c['disp']:,} ({pct(c['disp'], c['n'])})"),
        row("\\quad material", lambda c: f"{c['mat']:,} ({pct(c['mat'], c['n'])})"),
        row("\\quad confirmed", lambda c: f"{c['conf']:,} ({pct(c['conf'], c['n'])})"),
        r"\addlinespace",
        row("DMO heightened-risk", lambda c: f"{c['flag']:,} ({pct(c['flag'], c['n'])})"),
        r"\bottomrule", r"\end{tabular}",
        (r"\tabnote{Random historical draw (Section~\ref{sec:data}; seed 42), by "
         r"platform. Dispute rates are natural base rates in the sample (not the "
         r"case-control oversample used for fitting). ``DMO heightened-risk'' is the "
         r"share carrying a characteristic flagged by DMO Advisory 26-08.}"),
        r"\end{table}", "",
    ]
    (TAB_DIR / outfile).write_text("\n".join(lines))


# --------------------------------------------------- dollars at risk, by grade
def volume_table(outfile="volume_grade.tex", label="tab:volume_grade", target="confirmed"):
    """Within the representative sample, share of markets vs. share of dollar volume
    in each grade --- the 'dollars at risk' result for Section 6.2."""
    f = fit_grades(target=target)
    g, G, pop, letters, nig = f["g"], f["G"], f["pop"], f["letters"], f["not_ig_from"]
    rows, units, *_ = load()
    vol = np.array([(r.get("volume") or 0) for r in rows], float)
    gp, vp = g[pop], vol[pop]
    N, V = len(gp), vp.sum()

    def line(name, mask, bold=False):
        nm = int(mask.sum())
        pm, pv = 100 * nm / N, 100 * vp[mask].sum() / V
        tot = vp[mask].sum()
        cells = [name, f"{pm:.1f}", f"{pv:.1f}", f"\\${tot/1e6:,.0f}M"]
        if bold:
            cells = [f"\\textbf{{{c}}}" for c in cells]
        return " & ".join(cells) + " \\\\"

    body = []
    for k in range(G):
        body.append(line(letters[k], gp == k))
        if k == nig - 1:
            body.append(line("Investment grade", gp < nig, bold=True))
    body.append(line("Below investment grade", gp >= nig, bold=True))

    lines = [
        "% auto-generated by paper/scripts/generate_section6.py",
        r"\begin{table}[t]", r"\centering", r"\small",
        r"\renewcommand{\arraystretch}{1.05}",
        r"\caption{Where the money sits: markets vs.\ volume by grade}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{lccc}", r"\toprule",
        r"Grade & \% of markets & \% of volume & Total volume \\",
        r"\midrule", *body, r"\bottomrule", r"\end{tabular}",
        (r"\tabnote{Representative random sample (Section~\ref{sec:data}; $n=5{,}567$), "
         r"confirmed-trained grades (Table~\ref{tab:grade_tiers}). Columns are each grade's "
         r"share of all markets and of total dollar volume. Volume is descriptive here, "
         r"not an input to the grade.}"),
        r"\end{table}", "",
    ]
    (TAB_DIR / outfile).write_text("\n".join(lines))


def volume_robustness_table(outfile="volume_robustness.tex",
                            label="tab:volume_robustness", target="confirmed"):
    """Appendix companion to Table~\\ref{tab:grade_tiers}: the actual grade ladder ---
    each grade's share of markets, share of dollar volume, and total volume --- under
    each fitted scoring model, one stacked panel per model (Table 6-style ladder)."""
    from dispute_regression import EBMClassifier, HandLogit, HGBModel, SkLogit

    specs = [
        ("Gradient boosting (HGB, deployed)", dict(model=HGBModel())),
        ("Logistic", dict(model=HandLogit())),
        ("Lasso (L1)", dict(model=SkLogit(l1_ratio=1.0))),
        ("Ridge (L2)", dict(model=SkLogit(l1_ratio=0.0))),
        ("EBM", dict(model=EBMClassifier())),
    ]
    try:
        from dispute_regression import XGBClassifierModel
        specs.append(("XGBoost", dict(model=XGBClassifierModel())))
    except Exception as exc:  # noqa: BLE001
        print(f"  [skip] XGBoost panel omitted from volume robustness ({type(exc).__name__})")

    def panel(name, kw):
        f = fit_grades(target=target, **kw)
        g, G, pop, letters, nig = f["g"], f["G"], f["pop"], f["letters"], f["not_ig_from"]
        vol = np.array([(r.get("volume") or 0) for r in f["rows"]], float)
        gp, vp = g[pop], vol[pop]
        N, V = len(gp), vp.sum()

        def line(nm, mask, bold=False):
            pm = 100 * mask.sum() / N
            pv = 100 * vp[mask].sum() / V if V else float("nan")
            vals = [nm, f"{pm:.1f}", f"{pv:.1f}", f"\\${vp[mask].sum() / 1e6:,.0f}M"]
            if bold:
                vals = [f"\\textbf{{{c}}}" for c in vals]
            return "\\quad " + " & ".join(vals) + " \\\\"

        out = [f"\\multicolumn{{4}}{{l}}{{\\textbf{{Scoring model: {name}}}}} \\\\"]
        for k in range(G):
            out.append(line(letters[k], gp == k))
            if k == nig - 1:
                out.append(line("Investment grade", gp < nig, bold=True))
        out.append(line("Below investment grade", gp >= nig, bold=True))
        return out

    body = []
    for i, (name, kw) in enumerate(specs):
        if i:
            body += ["\\addlinespace", "\\midrule"]
        body += panel(name, kw)

    lines = [
        "% auto-generated by paper/scripts/generate_section6.py",
        r"\begin{table}[p]", r"\centering", r"\footnotesize",
        r"\renewcommand{\arraystretch}{1.0}",
        r"\caption{Where the money sits, by scoring model}",
        rf"\label{{{label}}}",
        r"\begin{tabular}{lccc}", r"\toprule",
        r"Grade & \% of markets & \% of volume & Total volume \\",
        r"\midrule", *body, r"\bottomrule", r"\end{tabular}",
        (r"\tabnote{Table~\ref{tab:grade_tiers} repeated under each fitted scoring model, "
         r"one panel per model: each grade's share of markets, share of dollar volume, and "
         r"total volume in the representative sample (confirmed-trained grades, grouped "
         r"70/30 split). The first panel is the deployed gradient-boosted grade.}"),
        r"\end{table}", "",
    ]
    (TAB_DIR / outfile).write_text("\n".join(lines))
    print(f"wrote tables/{outfile}")
    print(f"wrote tables/{outfile}")


# ----------------------------------------------------------- grade distribution
def grade_distribution_fig(outfile="grade_distribution.pdf", target="confirmed"):
    f = fit_grades(target=target)
    g, G, pop, letters, nig = f["g"], f["G"], f["pop"], f["letters"], f["not_ig_from"]
    gp = g[pop]
    N = len(gp)
    shares, los, his = [], [], []
    for k in range(G):
        p, lo, hi = _ci(int((gp == k).sum()), N)
        shares.append(p); los.append(lo); his.append(hi)
    ig_share, below = sum(shares[:nig]), sum(shares[nig:])

    # Figure 1 palette: investment grade = light blue, below IG = dark blue
    # (dark draws the eye to the finding); shared serif theme.
    IG, NIG, GRID = "#c9d6e3", "#33618f", "#dddddd"
    colors = [IG if k < nig else NIG for k in range(G)]
    err = np.array([[s - lo for s, lo in zip(shares, los)],
                    [hi - s for s, hi in zip(shares, his)]])

    from matplotlib.patches import Patch
    with plt.rc_context({"font.family": "serif", "font.size": 10,
                         "axes.linewidth": 0.6}):
        fig, ax = plt.subplots(figsize=(7.0, 4.2))
        x = np.arange(G)
        ax.set_axisbelow(True)
        ax.yaxis.grid(True, color=GRID, lw=0.6, zorder=0)
        ax.bar(x, shares, color=colors, width=0.70, zorder=2,
               edgecolor="white", linewidth=0.5)
        ax.errorbar(x, shares, yerr=err, fmt="none", ecolor="#444444",
                    elinewidth=0.9, capsize=3, zorder=3)
        for xi, s, hi in zip(x, shares, his):
            ax.text(xi, hi + 0.9, f"{s:.1f}", ha="center", va="bottom",
                    fontsize=8.5, color="#333333")
        # investment-grade boundary
        ax.axvline(nig - 0.5, color="#444444", lw=0.7, ls=(0, (4, 3)), zorder=1)

        ax.set_xticks(x); ax.set_xticklabels(letters)
        ax.set_ylabel("Share of representative market sample (%)", fontsize=9)
        ax.set_xlabel("Specification-quality grade", fontsize=9)
        ax.set_ylim(0, max(his) * 1.20)
        ax.tick_params(length=0)
        ax.spines[["top", "right"]].set_visible(False)

        fig.legend(handles=[Patch(color=IG, label=f"Investment grade ({ig_share:.0f}%)"),
                            Patch(color=NIG, label=f"Below investment grade ({below:.0f}%)")],
                   loc="upper center", ncol=2, fontsize=8.5, frameon=False,
                   bbox_to_anchor=(0.5, 1.04))
        fig.tight_layout(rect=(0, 0, 1, 0.96))
        FIG_DIR.mkdir(parents=True, exist_ok=True)
        fig.savefig(FIG_DIR / outfile, bbox_inches="tight")
        plt.close(fig)


def auc_prediction_fig(outfile="dispute_auc.pdf", target="confirmed"):
    """Out-of-sample AUC rising across dispute severity (all -> material ->
    confirmed), one line per model, faceted by platform. Models are colored by
    family --- gray = equal sum (baseline); blues = the linear logistic trio;
    greens = the nonlinear EBM/XGBoost pair --- with the '+volume' diagnostic
    dashed. Pooled/confirmed matches Table~\\ref{tab:dispute_models}."""
    m = auc_matrix(target)
    panels = [("(a) Polymarket — predictive", "Polymarket"),
              ("(b) Kalshi — concurrent", "Kalshi"),
              ("(c) Pooled", "Pooled")]
    sev = ["All", "Material", "Confirmed"]
    x = np.arange(3)
    # tuple: key, label, color, linestyle, marker, filled?, linewidth.
    # Families: gray baseline; blues = linear (logistic/L1/L2); greens =
    # nonlinear (EBM/XGBoost); muted purple dashed = +volume diagnostic.
    series = [
        ("equal",    "Equal sum",          "#9a9a9a", (0, (1, 2)), "o", False, 1.4),
        ("logistic", "Logistic",           "#3a6ea5", "-",         "o", True,  1.9),
        ("l1",       "Logistic (L1)",      "#79a8d0", "-",         "^", True,  1.4),
        ("l2",       "Logistic (L2)",      "#16467a", "-",         "v", True,  1.4),
        ("ebm",      "EBM",                "#4aa05e", "-",         "s", True,  1.9),
        ("hgb",      "HGB (deployed)",     "#b3541e", "-",         "*", True,  2.1),
        ("xgb",      "XGBoost",            "#226b34", "-",         "D", True,  1.5),
        ("volume",   "$+$ volume (diag.)", "#b48ec9", (0, (5, 3)), "P", False, 1.6),
    ]
    from matplotlib.lines import Line2D

    def _draw(ax, x, y, color, ls, mk, filled, lw):
        ax.plot(x, y, color=color, ls=ls, lw=lw, marker=mk, ms=5.5,
                markerfacecolor=(color if filled else "white"),
                markeredgecolor=color, markeredgewidth=1.2,
                zorder=3, clip_on=False)

    with plt.rc_context({"font.family": "serif", "font.size": 10,
                         "axes.linewidth": 0.7}):
        fig, axs = plt.subplots(1, 3, figsize=(11, 3.9), sharey=True)
        drawn = []
        for ax, (title, key) in zip(axs, panels):
            d = m[key]
            for s in series:
                skey = s[0]
                if skey not in d:
                    continue                       # e.g. xgb missing
                y = [v if v is not None else np.nan for v in d[skey]]
                _draw(ax, x, y, *s[2:])
                if s not in drawn:
                    drawn.append(s)
            ax.set_title(title, fontsize=11)
            ax.set_xticks(x); ax.set_xticklabels(sev)
            ax.set_xlim(-0.3, 2.3); ax.set_ylim(0.5, 1.0)
            ax.tick_params(length=0)
            ax.spines[["top", "right"]].set_visible(False)
        axs[0].set_ylabel("Out-of-sample AUC", fontsize=10)
        axs[0].text(-0.22, 0.508, "chance", fontsize=8, color="#999999",
                    style="italic", va="bottom", ha="left")
        handles = [Line2D([0], [0], color=c, ls=ls, lw=lw, marker=mk, ms=5.5,
                          markerfacecolor=(c if fl else "white"),
                          markeredgecolor=c, markeredgewidth=1.2, label=lab)
                   for _, lab, c, ls, mk, fl, lw in drawn]
        fig.legend(handles=handles, loc="upper center", ncol=len(drawn), fontsize=9,
                   frameon=False, bbox_to_anchor=(0.5, 1.07), handlelength=2.3,
                   columnspacing=1.5)
        fig.supxlabel("Dispute severity (nested: all $\\supset$ material $\\supset$ confirmed)",
                      fontsize=10, y=-0.02)
        fig.tight_layout(rect=(0, 0, 1, 0.95))
        FIG_DIR.mkdir(parents=True, exist_ok=True)
        fig.savefig(FIG_DIR / outfile, bbox_inches="tight")
        plt.close(fig)


SHORT_AXIS = {
    "predicate_ambiguity": "Predicate ambiguity",
    "entity_ambiguity": "Entity ambiguity",
    "temporal_precision": "Temporal precision",
    "source_specification": "Source specification",
    "source_quality": "Source quality",
    "edge_case_coverage": "Edge case coverage",
    "headline_rules_alignment": "Headline–rules alignment",
    "governing_body_engagement": "Governing body engagement",
    "structural": "Structural integrity",
}


def interpretability_figs(ebm_out="ebm_shapes.pdf", xgb_out="xgb_shap.pdf"):
    """Native interpretability displays for the two nonlinear models (appendix):
    EBM shape functions (per-axis effect curves --- its glass-box form) and an
    XGBoost SHAP beeswarm (the canonical black-box display). Both fit on the raw
    0--3 axis scores of the pooled confirmed sample, so the axes read directly."""
    import shap
    from dispute_regression import (
        LEARN_COLS, EBMClassifier, XGBClassifierModel, market_units,
    )
    from generate_regression_table import conf_sample

    sample = conf_sample(market_units("polymarket") + market_units("kalshi"))
    M = np.array([[u[c] for c in LEARN_COLS] for u in sample], float)   # raw 0--3
    y = np.array([u["disputed"] for u in sample], float)
    names = [SHORT_AXIS[c] for c in LEARN_COLS]

    # --- EBM shape functions (main-effects only, so the curves are pure) ---
    ebm = EBMClassifier(interactions=0).fit(M, y).clf
    g = ebm.explain_global()
    with plt.rc_context({"font.family": "serif", "font.size": 9,
                         "axes.linewidth": 0.7}):
        fig, axs = plt.subplots(3, 3, figsize=(9, 7.3), sharey=True)
        for i, ax in enumerate(axs.ravel()):
            d = g.data(i)
            edges, scores = np.array(d["names"]), np.array(d["scores"])
            xs = [0, 1, 2, 3]
            ys = [scores[min(np.digitize(k, edges[1:-1]), len(scores) - 1)] for k in xs]
            ax.axhline(0, color="#cccccc", lw=0.8, zorder=1)
            ax.plot(xs, ys, color="#2f5688", marker="o", ms=4, lw=1.8, zorder=3)
            ax.set_title(names[i], fontsize=9)
            ax.set_xticks(xs); ax.tick_params(length=0)
            ax.spines[["top", "right"]].set_visible(False)
        for ax in axs[-1, :]:
            ax.set_xlabel("Axis score (0–3)", fontsize=8)
        for ax in axs[:, 0]:
            ax.set_ylabel("Log-odds contribution", fontsize=8)
        fig.tight_layout()
        fig.savefig(FIG_DIR / ebm_out, bbox_inches="tight")
        plt.close(fig)

    # --- XGBoost SHAP summary as a layered-violin density (smooth per-axis
    #     distributions, colored by axis score) instead of individual dots ---
    xg = XGBClassifierModel().fit(M, y, groups=[u["group"] for u in sample]).clf.best_estimator_
    sv = shap.TreeExplainer(xg).shap_values(M)
    with plt.rc_context({"font.family": "serif", "font.size": 9}):
        # Wide aspect (longer x-axis) + finer color binning so the score gradient
        # reads smoothly rather than as coarse blotches.
        shap.summary_plot(sv, M, feature_names=names, plot_type="layered_violin",
                          show=False, plot_size=(11.5, 4.4),
                          layered_violin_max_num_bins=100,
                          color_bar_label="Axis score (0–3)")
        plt.savefig(FIG_DIR / xgb_out, bbox_inches="tight")
        plt.close("all")
    print(f"wrote figures/{ebm_out}, figures/{xgb_out}")


def main():
    # descriptives_table() removed from the paper; generator kept for reference.
    volume_robustness_table()
    grade_distribution_fig()
    interpretability_figs()


if __name__ == "__main__":
    main()
