#!/usr/bin/env python3
"""Grade-level agreement among the three grade versions (Section 5.3 + appendix):
the author's (human), the LLM's, and the blind-adjudicated gold standard.

The 300 hand-graded contracts carry both graders' axis scores. The adjudicated
(gold) axis vector replaces each adjudicated disagreement cell with the grader the
blind reviewer preferred (Section 5.1); unadjudicated single-point disagreements
are set to the two graders' midpoint. We push each version through the SAME grade
formula and compare the letters. The headline: the LLM tracks the gold grade at
least as closely as the human does.

Reads:  data/pilot_v07_results.json, data/ab_adjudication_key.csv,
        data/adjudication_final_verdicts.csv, data/full_grades.jsonl  (never modified)
Writes: paper/tables/grade_agreement.tex          (simple-sum fixed bands; main text)
        paper/tables/grade_agreement_quantile.tex (learned-composite octiles; appendix)
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))
sys.path.insert(0, str(ROOT / "paper" / "scripts"))
from parser.schema import spec_grade, TIER_ORDER  # noqa: E402
from dispute_regression import AXES  # noqa: E402

TAB = ROOT / "paper" / "tables"
IDX = {g: i for i, g in enumerate(TIER_ORDER)}


def gold_axes(pilot):
    """Per-contract adjudicated (gold) axis vector: agreed value where graders
    agree; the blind-preferred grader's value on adjudicated cells; midpoint on
    unadjudicated single-point disagreements."""
    key = {r["item"]: r for r in csv.DictReader(open(ROOT / "data" / "ab_adjudication_key.csv"))}
    verd = {r["item"]: r["preferred"]
            for r in csv.DictReader(open(ROOT / "data" / "adjudication_final_verdicts.csv"))}
    corr = {}
    for item, pref in verd.items():
        k = key.get(item)
        if k:
            corr[(k["contract_id"], k["axis"])] = int(k["human_score"] if pref == "human" else k["llm_score"])
    out = {}
    for cid, r in pilot.items():
        g = {}
        for a in AXES:
            hv, lv = int(r["human"][a]), int(r["llm"][a])
            g[a] = hv if hv == lv else corr.get((cid, a), (hv + lv) / 2)
        out[cid] = g
    return out


def _qwk(hi, li, k=8):
    O = np.zeros((k, k))
    for a, b in zip(hi, li):
        O[a, b] += 1
    w = np.array([[(i - j) ** 2 / (k - 1) ** 2 for j in range(k)] for i in range(k)])
    E = np.outer(O.sum(1), O.sum(0)) / O.sum()
    return 1 - (w * O).sum() / (w * E).sum()


def _rank(v):
    o = np.argsort(v, kind="mergesort"); r = np.empty(len(v)); r[o] = np.arange(len(v)); return r


def pair(ga, gb, va, vb, ig_idx):
    ia = [IDX[g] for g in ga]; ib = [IDX[g] for g in gb]
    return dict(
        exact=np.mean([a == b for a, b in zip(ia, ib)]),
        within1=np.mean([abs(a - b) <= 1 for a, b in zip(ia, ib)]),
        ig=np.mean([(a <= ig_idx) == (b <= ig_idx) for a, b in zip(ia, ib)]),
        qwk=_qwk(ia, ib),
        rho=float(np.corrcoef(_rank(va), _rank(vb))[0, 1]),
    )


def main():
    TAB.mkdir(parents=True, exist_ok=True)
    res = [r for r in json.load(open(ROOT / "data" / "pilot_v07_results.json")) if not r.get("error")]
    ok = lambda d: all(d.get(a) is not None for a in AXES)  # noqa: E731
    pilot = {r["id"]: r for r in res if ok(r["human"]) and ok(r["llm"])}
    gold = gold_axes(pilot)
    cids = list(pilot)

    # ---- simple-sum scores (Section 5.2) ----
    hsum = [sum(int(pilot[c]["human"][a]) for a in AXES) for c in cids]
    lsum = [sum(int(pilot[c]["llm"][a]) for a in AXES) for c in cids]
    gsum = [sum(gold[c][a] for a in AXES) for c in cids]
    hgf = [spec_grade(round(s)) for s in hsum]
    lgf = [spec_grade(round(s)) for s in lsum]
    ggf = [spec_grade(round(s)) for s in gsum]

    def pct(x):
        return f"{100 * x:.0f}\\%"

    def write_table(path, label, hg, lg, gg, hv, lv, gv, ig_idx, system, extra, note=""):
        HL = pair(hg, lg, hv, lv, ig_idx)
        HA = pair(hg, gg, hv, gv, ig_idx)
        LA = pair(lg, gg, lv, gv, ig_idx)
        rows = [("Within one letter", "within1"), ("Investment-grade call", "ig"),
                ("Spearman $\\rho$ (score)", "rho"), ("Quadratic weighted $\\kappa$", "qwk"),
                ("Exact letter", "exact")]
        lines = [
            "% auto-generated by paper/scripts/generate_grade_agreement.py",
            "\\begin{table}[t]", "\\centering", "\\small",
            f"\\caption{{{extra}}}", f"\\label{{{label}}}",
            "\\begin{tabular}{lccc}", "\\toprule",
            "Agreement metric & Human vs.\\ LLM & Human vs.\\ adj.\\ & LLM vs.\\ adj. \\\\",
            "\\midrule",
        ]
        for nm, kk in rows:
            f = (lambda v: f"{v:.2f}") if kk in ("rho", "qwk") else pct
            lines.append(f"{nm} & {f(HL[kk])} & {f(HA[kk])} & {f(LA[kk])} \\\\")
        lines += ["\\bottomrule", "\\end{tabular}"]
        if note:
            lines.append(f"\\tabnote{{{note}}}")
        lines += ["\\end{table}", ""]
        path.write_text("\n".join(lines))
        print(f"wrote {path.name}")

    n = len(cids)
    main_cap = f"Grade-level agreement: human, LLM, and adjudicated gold ($n={n}$)"
    main_note = (
        "Each contract graded three ways from the same simple-sum formula "
        "(Section~\\ref{sec:weighting}): author's axis scores, the LLM's, and the "
        "blind-adjudicated gold (Section~\\ref{sec:hlagree}). Mean score: human "
        f"{np.mean(hsum):.1f}, adjudicated {np.mean(gsum):.1f}, LLM {np.mean(lsum):.1f}."
    )
    write_table(TAB / "grade_agreement.tex", "tab:grade_agreement",
                hgf, lgf, ggf, hsum, lsum, gsum, IDX["B"], "simple sum", main_cap,
                note=main_note)


if __name__ == "__main__":
    main()
